name: Publish Package (OIDC)

on:
  push:
    branches:
      - Release

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # OIDC 필수
      contents: write   # Release 생성 필수
    environment:
      name: pypi        # GitHub Environments 이름과 동일

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist & wheel
        run: python -m build

      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        # with: 아무것도 넣지 말 것 (비밀번호/토큰 X)
      
      - name: Make a Release at Github
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/*